---
- include: install-yum.yml
  when: ansible_pkg_mgr == 'yum'

- include: install-apt.yml
  when: ansible_pkg_mgr == 'apt'

- name: Copy Memcached configuration.
  template:
    src: memcached.conf.j2
    dest: /etc/memcached.conf
    owner: root
    group: root
    mode: 0644
  notify: restart memcached

- name: Copy sysconfig Memcached configuration. # /etc/sysconfig/memcached
  template:
    src: memcached.sys.j2
    dest: /etc/sysconfig/memcached
    owner: root
    group: root
    mode: 0644
  notify: restart memcached

- name: Ensure Memcached is started and set to run on startup.
  service: name=memcached state=started enabled=yes
